services:
  - type: web
    name: swagger-ui
    env: docker
    plan: starter
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
    disk:
      name: swagger-data
      mountPath: /swagger-data
      sizeGB: 1
